### ISSUE TITLE
Issue with gradient formulation

### ISSUE THREAD

**Issue by nitneh** [Strateus/TripletChain#1]
I think, there is some issue in gradient calculation part:

  calculating n-p, p-a and a-n elementwise differences
        n_p_diff = n-p
        p_a_diff = p-a
        a_n_diff = a-n
 calculating Loss derivatives over a, n, p
        dLda = n_p_diff * 2 / N
        dLdp = p_a_diff * 2 / N
        dLdn = a_n_diff * 2 / N

If we calculate loss gradient with respect to a,p,n then these statements should be:

 calculating n-p, p-a and a-n elementwise differences
        n_p_diff = n-p
        p_a_diff = -a
        a_n_diff = a
  calculating Loss derivatives over a, n, p
        dLda = n_p_diff * 2 / N
        dLdp = p_a_diff * 2 / N
        dLdn = a_n_diff * 2 / N

Please correct me, if I am wrong...

**Comment by Strateus** [comment]
You can refer to this package: https://github.com/Atcold/torch-TripletEmbedding, i just worked out this code with Alfredo 1.5 years ago.
You can also check FaceNet paper: http://arxiv.org/abs/1503.03832v1

**Comment by nitneh** [comment]
Yeah... I have also opened the issue on https://github.com/Atcold/torch-TripletEmbedding/issues/6

This paper does not have any derivation or equation ...

Thanks for your time..

**Comment by nitneh** [comment]
Thanks .. I got my answer... ur formulation is without normalization... and I am doing the same with normalization... so both are correct...
